### ISSUE TITLE
can you help me？

### ISSUE THREAD

**Issue by liuluyang06** [hmcts/juror-api#273]
Can you help me? I saw this line in your code as well:
when(jpaQuery.orderBy(any(OrderSpecifier.class))).thenReturn(jpaQuery);

I also wrote this, but can not execute, the specific details of the problem, I published to the mock repository issues above, thanks for the answer!
https://github.com/mockito/mockito/issues/3329

**Comment by Ben-Edwards-cgi** [comment]
You should be able to bypass the need for this  by adding a default answer of RETURNS_SELF when you create your mock

mock(JPAQuery.class, withSettings().defaultAnswer(RETURNS_SELF));
